name: Deploy readme.txt to WordPress.org

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: WordPress.org plugin directory
      url: https://wordpress.org/plugins/salesfeed/

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            .wordpress-org
            readme.txt

      - name: Deploy
        uses: pronamic/action-wordpress-org-plugin-readme-deploy@main
        with:
          username: pronamic
          password: ${{ secrets.SVN_PASSWORD }}
          slug: salesfeed
